#!/bin/bash -x

upgrade_agent_transfer_list="upgradeagent.conf \
            dist \
            systemd/nvmeshupgradeagent.service"

print_help() {
    cat <<EOF
usage:

-h      --help              prints this help

-b      --branch            branch name

-c      --commit-id         commit id

-g      --change-id         change id

-d      --git-describe      git describe string

-S	    --sign-rpm	    sign the rpm

--build-number              package build number

--dist-tag		    distribution tag to include in the RPM name

--ubuntu		    create deb package for ubuntu
EOF
}

validate_buildrpm_dependencies_installed() {
    # Check if environment variable is set
    if [ -z "$BUILDRPM_DEPENDENCIES" ]; then
        echo "Error: BUILDRPM_DEPENDENCIES environment variable is not set or empty"
        return 1
    fi

    local missing_packages=()

    # Determine the package check command based on OS
    if [ -e /etc/redhat-release ]; then
        check_cmd="rpm -q"
    elif [[ "$(cat /etc/os-release 2>/dev/null)" =~ Ubuntu ]]; then
        check_cmd="dpkg -l"
    else
        echo "Error: Unable to determine OS type (neither RedHat nor Ubuntu detected)"
        return 1
    fi

    # Check each package
    for package in $BUILDRPM_DEPENDENCIES; do
        if ! $check_cmd "$package" >/dev/null 2>&1; then
            missing_packages+=("$package")
        fi
    done

    # If there are missing packages, report them and exit with error
    if [ ${#missing_packages[@]} -gt 0 ]; then
        echo "Error: The following packages are not installed:"
        printf '%s\n' "${missing_packages[@]}"
        return 1
    fi

    return 0
}

buildRPMSetupTree() {
    if test -e /etc/redhat-release; then
        echo "Building RPM on Redhat-based distro. Running rpmdev-setuptree"
        rpmdev-setuptree
    else
        echo "Building RPM on non Redhat-based distro. Assuming Ubuntu. Manually setting up $rpm_build_dir"
        mkdir -p $rpm_build_dir/{SPECS,BUILD,BUILDROOT,SOURCES,RPMS/$ARCH,SRPMS}
    fi
}

pkgDeb() {
    if $isUbuntu || [[ "$DISTRIBUTION_INFO" =~ "Ubuntu" ]]; then
        echo "Building Ubuntu deb package..."
        ubuntu_dir="ubuntu_deb_build"
        mkdir $ubuntu_dir
        cd $ubuntu_dir

        if [ $ARCH == aarch64 ]; then
            ATARGET=--target=arm64
        else
            ATARGET=
        fi

        alien --generate -k --scripts ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"* $ATARGET

        packDir=$packagePrefix-$rpm_version

        if [ -e $packDir/debian ]; then
            echo "Setting gzip compression..."
            sed -i -E "s/dh_builddeb$/dh_builddeb -- -Zgzip/g" $packDir/debian/rules

            cd $packDir
            dpkg-buildpackage -uc -us
            cd ..
            rm -rf $packDir
            cp *.deb ../
        fi

        cd ..
        rm -rf $ubuntu_dir
    fi
}

isUbuntu=false
buildNum="buildnumber" #default place holder for non-official build

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -h|--help)
    print_help
    exit 0
    ;;
    -b|--branch)
    branchName="$2"
    shift
    ;;
    -c|--commit-id)
    commitID="$2"
    shift
    ;;
    -g|--change-id)
    changeID="$2"
    shift
    ;;
    -d|--git-describe)
    describe="$2"
    shift
    ;;
    -S|--sign-rpm)
    signRPM=true
    ;;
    --dist-tag)
    distTag="$2"
    shift
    ;;
    --ubuntu)
    isUbuntu=true
    ;;
    --build-number)
    buildNum="$2"
    shift
    ;;
    *)
        # unknown option
        echo "Unknown option $key"
        print_help
        exit 1
        ;;
    esac
    shift # past argument or value
done

. ./buildrpm_dependencies.env
if ! validate_buildrpm_dependencies_installed; then
    echo "Package validation failed"
    exit 1
fi

if [ -z "$DISTRIBUTION_INFO" ]; then
    DISTRIBUTION_INFO=$(cat /etc/*release)
fi

if [ -z $commitID ]; then
    commitID=$(git log -n1 --format=%h)
fi

if [ -z $changeID ]; then
    changeID=$(git log -n1 --format=%b | awk '/^Change-Id: / {print $2}')
fi

if [ -z $branchName ]; then
    branchName=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
fi

if [ -z $distTag ]; then
    if [ -e /etc/redhat-release ]; then
        redhat_rel_content=$(cat /etc/redhat-release)
        if [[ "$redhat_rel_content" =~ ([0-9]+).([0-9]+) ]]; then
            minor_ver=${BASH_REMATCH[2]}
            rpm_dist_tag=$(rpm --eval='%{?dist}')
            if [ -z "$minor_ver" ] || [ -z "$rpm_dist_tag" ]; then
                echo "ERROR: cannot find the distribution version"
                exit 1
            fi

            # check where to place the minor version
            IFS='.' read -r -a rpm_dist_tag_arr <<<"$rpm_dist_tag"

            if [ ${#rpm_dist_tag_arr[@]} -eq 3 ]; then
                distTag=".${rpm_dist_tag_arr[1]}"_"$minor_ver"
            else
                distTag="$rpm_dist_tag"_"$minor_ver"
            fi
        fi
    else
        #not rhel related os - ubuntu or other
        os_release_content=$(cat /etc/os-release)
        if [[ "$os_release_content" =~ VERSION_ID=\"([^\"]*) ]]; then
            os_version_id=${BASH_REMATCH[1]}
            short_version_id=$(echo $os_version_id | tr -d .)

            if [[ "$os_release_content" =~ NAME=\"([^\"]*) ]]; then
                os_name=${BASH_REMATCH[1]}
                # convert to lower case
                lower_os_name=$(echo "$os_name" | awk '{print tolower($0)}')
                # remove spaces
                lower_os_name=${lower_os_name//[[:blank:]]/}
                distTag=".$lower_os_name$short_version_id"
            fi
        fi
    fi

    if [ -z "$distTag" ]; then
        echo "ERROR: could not find the distribution name and version to append to the RPM name"
    fi
fi

if [ -z $describe ]; then
    describe=$(git describe | cut -c 2-)
elif [[ $describe == v* ]]; then
    describe=$(echo $describe | cut -c 2-)
fi

IFS='-' read -ra gitDescribe <<<"$describe"

rpm_version="${gitDescribe[0]}"
rpm_release_num="${gitDescribe[1]}"
rpm_release="${rpm_release_num}$distTag.$buildNum"

echo "VERSION: $rpm_version RELEASE: $rpm_release"

rpm_build_dir=$(readlink -f ~/rpmbuild)
ARCH=$(uname -m)
echo "Building nvmesh upgrade agent RPM"
rpm=upgrade-agent
buildRPMSetupTree

cp rpmmacros $HOME/.rpmmacros

packagePrefix="nvmesh-${rpm}"
cp nvmesh-$rpm.spec ~/rpmbuild/SPECS/
rm ~/rpmbuild/RPMS/$ARCH/$packagePrefix*$ARCH.rpm

cd ..
rsync -aRPq --exclude=*.pyc $upgrade_agent_transfer_list ~/"rpmbuild/SOURCES/$packagePrefix"
cd RPM

rm -fr ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"*

rpmbuild -ba ~/rpmbuild/SPECS/nvmesh-$rpm.spec --define "commit_id $commitID" --define "change_id $changeID" --define "branch $branchName" \
--define "version $rpm_version" --define "release $rpm_release"
rpm_creation_retval=$?

cp ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"* .

rm -rf ~/rpmbuild/SPECS/nvmesh-$rpm.spec ~/"rpmbuild/SOURCES/$packagePrefix" ~/"rpmbuild/BUILD/"* ~/"rpmbuild/BUILDROOT/"*

if [ "$rpm_creation_retval" -eq "0" ] && [ "$signRPM" == true ]; then
    new_rpm="$packagePrefix*$rpm_version-$rpm_release*.rpm"
    echo "Signing RPM..."
    rpm --addsign $new_rpm
    if [ "$?" -ne "0" ]; then
        echo "Failed to sign RPM!"
    fi
fi

pkgDeb
